name: "[Build]"

on:
  workflow_call:
    inputs:
      enabled:
        type: boolean
        default: true

jobs:
  build:
    name: Build packages [${{ matrix.host.platform }}]
    if: inputs.enabled
    strategy:
      fail-fast: false
      matrix:
        host:
          - platform: x86_64-linux
            runs-on: ubuntu-24.04
          - platform: aarch64-linux
            runs-on: ubuntu-24.04-arm

    runs-on: ${{ matrix.host.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build packages
        run: |
          result_path=build/${PLATFORM}.txt
          result=$(cat "$result_path")
          echo "$result_path: $result"
          test "$result" = "success"
        env:
          PLATFORM: ${{ matrix.host.platform }}

      - name: Run package tests
        run: |
          result_path=test/${PLATFORM}.txt
          result=$(cat "$result_path")
          echo "$result_path: $result"
          test "$result" = "success"
        env:
          PLATFORM: ${{ matrix.host.platform }}

      - name: Show failed processes
        if: failure()
        run: |
          echo "failed..."
