name: Build

on:
  push:
    branches:
      - main
      - "build/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  check:
    uses: ./.github/workflows/_check.yml

  build:
    needs: [check]
    uses: ./.github/workflows/_build.yml
    with:
      enabled: ${{ github.repository == 'brioche-dev/gh-actions-test' }}

  publish:
    name: Publish packages
    needs: [build]
    if: github.repository == 'brioche-dev/gh-actions-test' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish packages
        run: |
          echo "publish"
          for file in build/*.txt test/*.txt check; do
            echo "$file: $(cat "$file")"
          done
