name: Build

on:
  push:
    branches:
      - "build/**"
  pull_request:
  merge_group:
    types:
        - checks_requested

jobs:
  check:
    uses: ./.github/workflows/_check.yml

  build:
    needs: [check]
    uses: ./.github/workflows/_build.yml
    with:
      enabled: ${{ github.repository == 'brioche-dev/gh-actions-test' && (github.event_name == 'push' || github.event_name == 'merge_group')}}
