name: Build

on:
  push:
    branches:
      - main
      - "build/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  check:
    uses: ./.github/workflows/_check.yml

  build:
    needs: [check]
    uses: ./.github/workflows/_build.yml
    with:
      enabled: ${{ github.repository == 'brioche-dev/brioche-packages' }}

  publish:
    name: Publish packages
    needs: [build]
    if: github.repository == 'brioche-dev/brioche-packages' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Brioche
        run: |
          mkdir -p ~/.local/bin
          curl -L https://development-content.brioche.dev/github.com/brioche-dev/brioche/branches/main/x86_64-linux/brioche -o ~/.local/bin/brioche
          chmod +x ~/.local/bin/brioche
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Publish packages
        run: |
          echo "publish"
          for file in build/*.txt test/*.txt check; do
            echo "$file: $(cat "$file")"
          done
