name: Publish

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  check:
    uses: ./.github/workflows/_check.yml

  build:
    needs: [check]
    uses: ./.github/workflows/_build.yml

  publish:
    name: Publish packages
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files
        run: |
          ls -l files/

      - name: Publish packages
        run: |
          echo "publish"
          for file in build/*.txt test/*.txt check; do
            echo "$file: $(cat "$file")"
          done

